services:
  database:
    build:
      context: ./DATABASE
      dockerfile: dockerfile
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - ./VOLUMES/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  git-server:
    build:
      context: ./GIT-SERVER
      dockerfile: Dockerfile
    container_name: git_server
    volumes:
      - ./VOLUMES/repositorys:/srv/git
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    build:
      context: ./WEB/BACKEND
      dockerfile: Dockerfile
    container_name: express_backend
    working_dir: /app
    volumes:
      - ./WEB/BACKEND/CODE:/app
      - ./VOLUMES/repositorys:/srv/git
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - database
      - git-server

  frontend:
    build:
      context: ./WEB/FRONTEND
      dockerfile: Dockerfile
    container_name: react_frontend
    working_dir: /app
    volumes:
      - ./WEB/FRONTEND/CODE:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  database:
  repositorys:

networks:
  app-network:
    driver: bridge
