version: "3.9"

services:
  postgres:
    build:
      context: ./DATABASE
      dockerfile: Dockerfile
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  backend:
    build:
      context: ./WEB/BACKEND
      dockerfile: Dockerfile
    container_name: backend_service
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres_db:5432/myuser
    depends_on:
      - postgres
    ports:
      - "5000:5000"
      - "7005:7005"
    volumes:
      - ./WEB/BACKEND:/app
      - /app/node_modules
    networks:
      - app_network

  frontend:
    build:
      context: ./WEB/FRONTEND
      dockerfile: Dockerfile
    container_name: frontend_service
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./WEB/FRONTEND:/app
      - /app/node_modules
    networks:
      - app_network

  git_server:
    build:
      context: ./GIT-SERVER
      dockerfile: Dockerfile
    container_name: git_server
    depends_on:
      - backend
    ports:
      - "9418:9418"  # Corrected comment
    volumes:
      - ./GIT-SERVER:/app
      - /app/node_modules
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pg_data:
