version: "3.9"

services:
  database:
    build:
      context: ./DATABASE
      dockerfile: dockerfile
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - ./VOLUMES/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  git-server:
    build:
      context: ./GIT-SERVER
      dockerfile: Dockerfile
    container_name: git_server
    volumes:
      - ./VOLUMES/repositorys:/srv/git
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    build:
      context: ./WEB/BACKEND
      dockerfile: Dockerfile
    container_name: express_backend
    working_dir: /app
    volumes:
      - ./WEB/BACKEND/CODE:/app                # project source (bind mount)
      - ./VOLUMES/repositorys:/srv/git         # shared Git repos
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    depends_on:
      - database
      - git-server
    networks:
      - app-network

  frontend:
    build:
      context: ./WEB/FRONTEND
      dockerfile: Dockerfile
    container_name: react_frontend
    working_dir: /app
    volumes:
      - ./WEB/FRONTEND/CODE:/app
      - /app/node_modules                      # (unchanged; fix later if desired)
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  database:
  repositorys:
  backend_cache:                               # ⬅️ named cache volume

networks:
  app-network:
    driver: bridge
