version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pg_data:/var/lib/postgresql/data # Persist PostgreSQL data
    ports:
      - "5432:5432"
    networks:
      - app_network

  backend:
    build:
      context: ./WEB/BACKEND
      dockerfile: Dockerfile
    container_name: backend_service
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres_db:5432/mydb
    depends_on:
      - postgres
    ports:
      - "5000:5000"
      - "7005:7005"
    volumes:
      - ./WEB/BACKEND:/app # Syncs backend code between host and container
      - /app/node_modules # Keeps node_modules inside the container
    networks:
      - app_network

  frontend:
    build:
      context: ./WEB/FRONTEND
      dockerfile: Dockerfile
    container_name: frontend_service
    depends_on:
      - backend
    ports:
      - "3000:3000"
      
    volumes:
      - ./WEB/FRONTEND:/app # Syncs frontend code between host and container
      - /app/node_modules # Keeps node_modules inside the container
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pg_data:
